apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luanime
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - anime.lubax.net
      secretName: luanime-tls
  rules:
    - host: anime.lubax.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: luanime
                port:
                  number: 80
